import React,{useEffect,useState} from 'react';
import {Save,Server,ShieldAlert,Power,RefreshCw} from 'lucide-react';
import {ApiError,fetchControlSettings,saveControlSettings,updateEngineControls,getBackendBaseUrl} from '../api/client';
import {ControlCenterSettings,ModeRiskSettings,TradingMode} from '../api/types';
import {useAuth} from '../context/AuthContext';
const blank:ModeRiskSettings={max_risk_per_trade_pct:0,max_trades_per_day:0,max_daily_loss:0,max_concurrent_trades:0,session_start_utc:null,session_end_utc:null};
export default function ControlCenter(){
 const {connectionStatus}=useAuth(); const [settings,setSettings]=useState<ControlCenterSettings|null>(null); const [scalping,setScalping]=useState(blank); const [intraday,setIntraday]=useState(blank); const [state,setState]=useState<'loading'|'ready'|'saving'|'saved'|'unauthorized'|'disconnected'|'timeout'|'error'|'not_configured'>('loading'); const [message,setMessage]=useState('');
 const classify=(e:unknown)=>{if(e instanceof ApiError)return e.kind==='unauthorized'?'unauthorized':e.kind==='timeout'?'timeout':e.kind==='network'||e.kind==='configuration'?'disconnected':'error';return 'error'};
 const load=async()=>{setState('loading');setMessage('');try{const x=await fetchControlSettings();setSettings(x);setScalping(x.risk.scalping);setIntraday(x.risk.intraday);setState('ready')}catch(e){setState(classify(e));setMessage(e instanceof Error?e.message:'Unable to load settings')}}; useEffect(()=>{void load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setState('saving');try{const x=await saveControlSettings({scalping,intraday});setSettings(x);setScalping(x.risk.scalping);setIntraday(x.risk.intraday);setState('saved');setMessage('Settings persisted to backend.')}catch(err){setState(classify(err));setMessage(err instanceof Error?err.message:'Save failed')}};
 const control=async(key:'scalping_engine_enabled'|'intraday_engine_enabled'|'auto_trade_enabled'|'emergency_stop',value:boolean)=>{try{await updateEngineControls({[key]:value});await load()}catch(e){setState(classify(e));setMessage(e instanceof Error?e.message:'Control action failed')}};
 const field=(label:string,key:keyof ModeRiskSettings,value:ModeRiskSettings,setter:(v:ModeRiskSettings)=>void)=><label className="block"><span className="text-[10px] uppercase font-mono text-slate-400">{label}</span><input type="number" step="0.1" value={(value[key]??'') as any} onChange={e=>setter({...value,[key]:Number(e.target.value)})} className="mt-1 w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-xs text-white"/></label>;
 const profile=(title:string,value:ModeRiskSettings,setter:(v:ModeRiskSettings)=>void)=><div className="bg-slate-900 border border-slate-850 rounded-xl p-5"><h3 className="text-base font-bold text-white mb-4">{title}</h3><div className="grid grid-cols-2 gap-4">{field('Max risk per trade %','max_risk_per_trade_pct',value,setter)}{field('Max trades per day','max_trades_per_day',value,setter)}{field('Max daily loss','max_daily_loss',value,setter)}{field('Max concurrent trades','max_concurrent_trades',value,setter)}</div><div className="mt-4 text-xs text-slate-500">Session restriction: {value.session_start_utc&&value.session_end_utc?`${value.session_start_utc}–${value.session_end_utc} UTC`:'Not configured'}</div></div>;
 return <div className="space-y-6"><div className="bg-slate-900 border border-slate-850 rounded-xl p-5 flex justify-between gap-4"><div><h1 className="text-xl font-bold text-white">Control Center</h1><p className="text-xs text-slate-400 mt-1">Backend-persisted Demo settings and honest engine controls.</p></div><button onClick={()=>void load()} className="px-3 py-2 bg-slate-800 text-white rounded-lg text-xs flex gap-2"><RefreshCw className="h-4 w-4"/>Reload</button></div>
 {state==='loading'?<div className="p-8 text-center text-slate-400">Loading backend settings…</div>:!settings?<div className="p-8 bg-slate-900 rounded-xl text-center text-rose-400">{state.replace('_',' ')}: {message}</div>:<form onSubmit={save} className="space-y-6"><div className="grid lg:grid-cols-2 gap-6">{profile('Scalping Risk Limits',scalping,setScalping)}{profile('Intraday Risk Limits',intraday,setIntraday)}</div>
 <div className="grid lg:grid-cols-2 gap-6"><div className="bg-slate-900 border border-slate-850 rounded-xl p-5"><h3 className="font-bold text-white flex gap-2"><Power className="h-5 w-5 text-emerald-400"/>Engine Controls</h3>{([['scalping_engine_enabled','Scalping Engine'],['intraday_engine_enabled','Intraday Engine'],['auto_trade_enabled','Auto Trade'],['emergency_stop','Emergency Stop']] as const).map(([k,l])=><label key={k} className="mt-4 flex justify-between text-sm text-slate-300"><span>{l}</span><input type="checkbox" checked={settings.engine_control[k as 'scalping_engine_enabled'|'intraday_engine_enabled'] ?? settings.execution_control[k as 'auto_trade_enabled'|'emergency_stop']} onChange={e=>void control(k,e.target.checked)}/></label>)}</div>
 <div className="bg-slate-900 border border-slate-850 rounded-xl p-5"><h3 className="font-bold text-white flex gap-2"><Server className="h-5 w-5 text-indigo-400"/>Backend Status</h3><div className="mt-4 space-y-2 text-xs text-slate-400"><p>API: <span className="text-white">{getBackendBaseUrl()??'Not configured'}</span></p><p>Connection: <span className="text-white capitalize">{connectionStatus}</span></p><p>System mode: <span className="text-emerald-400 font-bold">Demo only</span></p><p>State: <span className="text-white capitalize">{state}</span></p>{message&&<p className={state==='saved'?'text-emerald-400':'text-rose-400'}>{message}</p>}</div></div></div>
 <button disabled={state==='saving'} className="px-5 py-3 bg-emerald-500 text-slate-950 rounded-lg font-bold flex items-center gap-2"><Save className="h-4 w-4"/>{state==='saving'?'Saving…':'Save Mode Settings'}</button></form>}</div>
}
