import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, RefreshCw, Filter, Target, AlertTriangle } from 'lucide-react';
import { ApiError, fetchPerformanceAnalysis } from '../api/client';
import { PerformanceAnalysisData, PerformanceFilters, PerformanceSummaryMetric } from '../api/types';

const fmt=(v:number|null,d=2)=>v==null?'N/A':v.toFixed(d);
const today=()=>{const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);return {start:s.toISOString(),end:e.toISOString()};};
function Card({title,m}:{title:string;m:PerformanceSummaryMetric}){return <div className="bg-slate-900 border border-slate-800 rounded-xl p-4"><div className="text-xs uppercase tracking-wider text-slate-400 font-bold mb-3">{title}</div><div className="grid grid-cols-2 gap-3 text-xs"><div>Total <b className="text-white float-right">{m.total_trades}</b></div><div>Win Rate <b className="text-white float-right">{fmt(m.win_rate)}%</b></div><div>W / L / BE <b className="text-white float-right">{m.wins}/{m.losses}/{m.breakeven}</b></div><div>Realized PnL <b className={m.realized_pnl!=null&&m.realized_pnl<0?'text-rose-400 float-right':'text-emerald-400 float-right'}>{fmt(m.realized_pnl)}</b></div><div>Avg PnL <b className="text-white float-right">{fmt(m.average_realized_pnl)}</b></div><div>Avg R:R <b className="text-white float-right">{fmt(m.average_risk_reward)}</b></div><div>Best / Worst <b className="text-white float-right">{fmt(m.best_trade)} / {fmt(m.worst_trade)}</b></div><div>SL / TP <b className="text-white float-right">{m.stop_loss_hit_count}/{m.take_profit_hit_count}</b></div><div>Manual / E-Stop <b className="text-white float-right">{m.manual_close_count}/{m.emergency_stop_count}</b></div></div></div>}
export default function PerformanceStrategy(){
 const [data,setData]=useState<PerformanceAnalysisData|null>(null); const [state,setState]=useState<'loading'|'ready'|'empty'|'error'|'unauthorized'>('loading'); const [error,setError]=useState('');
 const initial=useMemo(today,[]); const [filters,setFilters]=useState<PerformanceFilters>(initial);
 const load=async()=>{setState('loading');setError('');try{const d=await fetchPerformanceAnalysis(filters);setData(d);setState(d.trades.length?'ready':'empty');}catch(e){setData(null);setError(e instanceof Error?e.message:'Backend request failed.');setState(e instanceof ApiError&&e.kind==='unauthorized'?'unauthorized':'error');}};
 useEffect(()=>{void load();},[]);
 return <main className="flex-1 overflow-y-auto bg-slate-950 p-4 md:p-6"><div className="max-w-[1600px] mx-auto space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-white flex items-center gap-2"><BarChart3 className="text-emerald-400"/>Performance & Strategy</h1><p className="text-xs text-slate-400 mt-1">Canonical persisted trade history only.</p></div><button onClick={()=>void load()} className="px-3 py-2 rounded-lg bg-emerald-500 text-slate-950 text-xs font-bold flex items-center gap-2"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
 <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 grid grid-cols-1 md:grid-cols-7 gap-3"><input type="datetime-local" className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" onChange={e=>setFilters(f=>({...f,start:e.target.value?new Date(e.target.value).toISOString():undefined}))}/><input type="datetime-local" className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" onChange={e=>setFilters(f=>({...f,end:e.target.value?new Date(e.target.value).toISOString():undefined}))}/><select className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" value={filters.mode||''} onChange={e=>setFilters(f=>({...f,mode:(e.target.value||undefined) as any}))}><option value="">All modes</option><option value="scalping">Scalping</option><option value="intraday">Intraday</option><option value="unknown">Unknown</option></select><select className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" value={filters.strategy||''} onChange={e=>setFilters(f=>({...f,strategy:e.target.value||undefined}))}><option value="">All strategies</option>{data?.strategies.map(x=><option key={x}>{x}</option>)}</select><select className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" value={filters.status||''} onChange={e=>setFilters(f=>({...f,status:e.target.value||undefined}))}><option value="">All statuses</option>{data?.statuses.map(x=><option key={x}>{x}</option>)}</select><select className="bg-slate-950 border border-slate-700 rounded p-2 text-xs" value={filters.exitReason||''} onChange={e=>setFilters(f=>({...f,exitReason:e.target.value||undefined}))}><option value="">All exit reasons</option>{data?.exit_reasons.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>void load()} className="bg-slate-800 border border-slate-700 rounded p-2 text-xs font-bold flex items-center justify-center gap-2"><Filter className="h-4 w-4"/>Apply</button></div>
 {state==='loading'&&<div className="p-10 text-center text-slate-400">Loading real performance data…</div>}{state==='unauthorized'&&<div className="p-10 text-center text-amber-400">Unauthorized session.</div>}{state==='error'&&<div className="p-10 text-center text-rose-400">{error}</div>}{state==='empty'&&<div className="p-10 text-center text-slate-400">No persisted trades match this range.</div>}
 {data&&state==='ready'&&<><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4"><Card title="Scalping" m={data.summaries.scalping}/><Card title="Intraday" m={data.summaries.intraday}/><Card title="Unknown" m={data.summaries.unknown}/><Card title="Combined" m={data.summaries.combined}/></div><div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden"><div className="p-4 border-b border-slate-800 font-bold text-sm flex items-center gap-2"><Target className="h-4 w-4 text-emerald-400"/>Trade Outcome Analysis</div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-950 text-slate-400"><tr>{['Trade','Mode','Status','Result','PnL','Exit reason','Analysis','Closed'].map(h=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{data.trades.map(t=><tr key={t.trade_id} className="border-t border-slate-800"><td className="p-3"><b>{t.symbol}</b><div className="text-slate-500 font-mono">{t.trade_id}</div></td><td className="p-3 capitalize">{t.mode||'Unknown'}</td><td className="p-3">{t.status}</td><td className="p-3">{t.result||'N/A'}</td><td className="p-3">{fmt(t.realized_pnl)}</td><td className="p-3">{t.close_reason||'N/A'}</td><td className="p-3 max-w-md text-slate-400">{t.exit_analysis||t.operator_summary||'N/A'}</td><td className="p-3">{t.closed_time?new Date(t.closed_time).toLocaleString():'N/A'}</td></tr>)}</tbody></table></div></div><div className="text-[11px] text-slate-500 flex items-center gap-2"><AlertTriangle className="h-3.5 w-3.5"/>Strategy is N/A for records where the backend did not persist a strategy. No retrospective explanation is generated.</div></>}
 </div></main>;
}
