import React, { useMemo, useState } from 'react';
import { AlertCircle, Bell, RefreshCw, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';

function StatePanel({ title, detail }: { title: string; detail?: string | null }) {
  return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-10 text-center"><AlertCircle className="mx-auto mb-3 text-slate-500" size={30} /><div className="font-bold text-slate-200">{title}</div>{detail && <div className="mt-2 text-sm text-slate-500">{detail}</div>}</div>;
}

function value(value: unknown, suffix = '') {
  return value === null || value === undefined || value === '' ? 'N/A' : `${value}${suffix}`;
}

export default function Signals() {
  const { signalsResponse, signalsState, signalsError, refreshSignals, navigate, setSelectedSymbol } = useApp();
  const [search, setSearch] = useState('');
  const [direction, setDirection] = useState<'all' | 'buy' | 'sell'>('all');

  const signals = useMemo(() => (signalsResponse?.signals ?? []).filter((signal) => {
    const symbolMatch = !search || signal.symbol.toLowerCase().includes(search.toLowerCase());
    const directionMatch = direction === 'all' || signal.direction === direction;
    return (signal.status === 'armed' || signal.status === 'watching') && symbolMatch && directionMatch;
  }), [signalsResponse, search, direction]);

  const openChart = (symbol: string) => {
    setSelectedSymbol(symbol.replace('USDT', '/USDT') as never);
    navigate('chart');
  };

  return (
    <div className="p-4 md:p-6 space-y-5">
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div><h1 className="text-2xl font-black text-white flex items-center gap-2"><Bell className="text-amber-400" /> AI Signals</h1><p className="mt-1 text-sm text-slate-500">Saved actionable signals generated by the canonical backend</p></div>
        <button onClick={() => void refreshSignals()} disabled={signalsState === 'loading'} className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50 flex items-center gap-2"><RefreshCw size={16} className={signalsState === 'loading' ? 'animate-spin' : ''} /> Refresh</button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs uppercase text-slate-500">Actionable signals</div><div className="mt-1 text-2xl font-black text-white">{signals.length}</div></div>
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs uppercase text-slate-500">Mode</div><div className="mt-1 text-lg font-black text-white capitalize">{signalsResponse?.filters.mode ?? 'N/A'}</div></div>
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs uppercase text-slate-500">Source</div><div className="mt-1 text-lg font-black text-white">FastAPI backend</div></div>
      </div>

      <div className="flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-500" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Filter symbol" className="w-full rounded-lg border border-slate-800 bg-slate-900 py-2.5 pl-9 pr-3 text-sm" /></div><select value={direction} onChange={(e) => setDirection(e.target.value as 'all' | 'buy' | 'sell')} className="rounded-lg border border-slate-800 bg-slate-900 px-3 py-2.5 text-sm"><option value="all">All directions</option><option value="buy">Buy</option><option value="sell">Sell</option></select></div>

      {signalsState === 'loading' && <StatePanel title="Loading backend signals…" />}
      {signalsState === 'unauthorized' && <StatePanel title="Unauthorized" detail={signalsError} />}
      {signalsState === 'disconnected' && <StatePanel title="Backend disconnected or timed out" detail={signalsError} />}
      {signalsState === 'backend_error' && <StatePanel title="Backend error" detail={signalsError} />}
      {(signalsState === 'empty' || (signalsState === 'ready' && signals.length === 0)) && <StatePanel title="No backend signals ready to review" detail="Rejected, skipped, and failed candidates remain on the Scanner page." />}

      {signalsState === 'ready' && signals.length > 0 && <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{signals.map((signal) => {
        const detail = signal as typeof signal & {
          higher_timeframe?: string | null; stop_loss?: number | null; take_profit?: number | null;
          risk_reward?: number | null; score?: number | null; confidence?: number | null; htf_score?: number | null;
        };
        return (
          <div key={signal.signal_id} className="rounded-xl border border-slate-800 bg-slate-900 p-5">
            <div className="flex items-start justify-between gap-3"><div><div className="text-lg font-black text-white">{signal.symbol}</div><div className="mt-1 text-xs text-slate-500 capitalize">{signal.mode} · {signal.timeframe} / {detail.higher_timeframe ?? 'N/A'} · {signal.strategy}</div></div><div className={`rounded-md border px-2 py-1 text-xs font-black ${signal.direction === 'buy' ? 'border-emerald-900 bg-emerald-950/30 text-emerald-400' : 'border-rose-900 bg-rose-950/30 text-rose-400'}`}>{signal.direction.toUpperCase()}</div></div>
            <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Grade</span><div className="mt-1 font-bold">{signal.grade}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Score</span><div className="mt-1 font-bold">{value(detail.score)}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Confidence</span><div className="mt-1 font-bold">{value(detail.confidence, '%')}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Status</span><div className="mt-1 font-bold uppercase">{signal.status}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Entry</span><div className="mt-1 font-bold">{value(signal.entry_price)}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Stop Loss</span><div className="mt-1 font-bold text-rose-300">{value(detail.stop_loss)}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Take Profit</span><div className="mt-1 font-bold text-emerald-300">{value(detail.take_profit)}</div></div>
              <div className="rounded-lg bg-slate-950 p-2"><span className="text-slate-500">Risk : Reward</span><div className="mt-1 font-bold">{detail.risk_reward ? `1:${detail.risk_reward}` : 'N/A'}</div></div>
            </div>
            <div className="mt-4 rounded-lg border border-slate-800 bg-slate-950/60 p-3 text-sm leading-relaxed text-slate-300">{signal.reason}</div>
            <button onClick={() => openChart(signal.symbol)} className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 py-2 text-sm font-bold hover:border-slate-500">Open Chart</button>
          </div>
        );
      })}</div>}
    </div>
  );
}
